// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDze2CJ301Wj_ETRdXozkryK7c0yRIO64Y',
    appId: '1:100393572806:web:22bd453e7dad76e1c8fac7',
    messagingSenderId: '100393572806',
    projectId: 'nuvia-91973',
    authDomain: 'nuvia-91973.firebaseapp.com',
    storageBucket: 'nuvia-91973.firebasestorage.app',
    measurementId: 'G-GJHP1J3GQJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAD3OTAjNArWopGu5GWi42oYWHEG7v_RfI',
    appId: '1:100393572806:android:2d5248abe791efdec8fac7',
    messagingSenderId: '100393572806',
    projectId: 'nuvia-91973',
    storageBucket: 'nuvia-91973.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCf78CSb5rBSPCULuDGU9XJagjey6_aCCA',
    appId: '1:100393572806:ios:7ff80f9dd11ddf57c8fac7',
    messagingSenderId: '100393572806',
    projectId: 'nuvia-91973',
    storageBucket: 'nuvia-91973.firebasestorage.app',
    iosClientId: '100393572806-ui6327ktlipgm3qabg48jul4u1l161et.apps.googleusercontent.com',
    iosBundleId: 'com.example.nouuuu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCf78CSb5rBSPCULuDGU9XJagjey6_aCCA',
    appId: '1:100393572806:ios:7ff80f9dd11ddf57c8fac7',
    messagingSenderId: '100393572806',
    projectId: 'nuvia-91973',
    storageBucket: 'nuvia-91973.firebasestorage.app',
    iosClientId: '100393572806-ui6327ktlipgm3qabg48jul4u1l161et.apps.googleusercontent.com',
    iosBundleId: 'com.example.nouuuu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDze2CJ301Wj_ETRdXozkryK7c0yRIO64Y',
    appId: '1:100393572806:web:a344f019ec4043d6c8fac7',
    messagingSenderId: '100393572806',
    projectId: 'nuvia-91973',
    authDomain: 'nuvia-91973.firebaseapp.com',
    storageBucket: 'nuvia-91973.firebasestorage.app',
    measurementId: 'G-N5SD1806N3',
  );
}
