import 'package:flutter/material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_localizations/flutter_localizations.dart';
import 'package:go_router/go_router.dart';
import 'package:provider/provider.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // This will be generated by FlutterFire CLI

// Import screens
import 'presentation/screens/splash.dart';
import 'presentation/screens/onboarding.dart';
import 'presentation/screens/auth/log_in.dart';
import 'presentation/screens/auth/sign_up.dart';
import 'presentation/screens/home/home.dart';
import 'presentation/screens/car/details.dart';
import 'presentation/screens/car/BookCarScreen.dart';
import 'presentation/screens/car/PopularCarsScreen.dart';
import 'presentation/screens/home/BottomNavigationBar/profile.dart';
import 'presentation/screens/home/CompleteProfileScreen.dart';
import 'presentation/screens/payment/PaymentMethodsScreen.dart';
import 'presentation/screens/payment/AddCardScreen.dart';
import 'presentation/screens/car/SearchScreen.dart';
import 'presentation/screens/home/ExploreScreen.dart';
import 'presentation/screens/home/BottomNavigationBar/MyBookingsScreen.dart';
import 'presentation/screens/home/BottomNavigationBar/ChatScreen.dart';
import 'presentation/screens/home/notifications.dart';
import 'presentation/screens/home/BottomNavigationBar/FavoritesScreen.dart';
import 'presentation/screens/home/EnterLocationScreen.dart';
import 'presentation/screens/home/AppBottomNavigation.dart';
import 'presentation/screens/home/BottomNavigationBar/DocumentUploadScreen.dart';
import 'presentation/screens/payment/EReceiptScreen.dart';
import 'presentation/screens/payment/PaymentSuccessScreen.dart';
import 'presentation/screens/payment/ReviewSummaryScreen.dart';

// Import providers
import 'providers/ThemeProvider.dart';
import 'providers/LocaleProvider.dart';
import 'providers/auth.dart';
import 'providers/LocationProvider.dart';

// Import for localization
import 'l10n/AppLocalizations.dart';

// Safety wrapper to prevent crashes from initialization errors
class SafeAppWrapper extends StatelessWidget {
  final Widget child;

  const SafeAppWrapper({Key? key, required this.child}) : super(key: key);

  @override
  Widget build(BuildContext context) {
    try {
      return child;
    } catch (e) {
      debugPrint('Error in app initialization: $e');
      return MaterialApp(
        home: Scaffold(
          backgroundColor: Colors.white,
          body: Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(Icons.error_outline, color: Colors.red, size: 48),
                SizedBox(height: 16.h),
                Text(
                  'App Initialization Error',
                  style: TextStyle(fontSize: 20.sp, fontWeight: FontWeight.bold),
                ),
                SizedBox(height: 16.h),
                Text(
                  'Please restart the application',
                  style: TextStyle(fontSize: 16.sp),
                ),
              ],
            ),
          ),
        ),
      );
    }
  }
}

void main() async {
  // Ensure Flutter is initialized
  WidgetsFlutterBinding.ensureInitialized();

  // Initialize Firebase
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  // Initialize shared preferences
  final prefs = await SharedPreferences.getInstance();

  runApp(
    MultiProvider(
      providers: [
        ChangeNotifierProvider(create: (_) => ThemeProvider()),
        ChangeNotifierProvider(create: (_) => LocaleProvider()),
        ChangeNotifierProvider(create: (_) => AuthProvider()),
        ChangeNotifierProvider(
          create: (_) {
            final provider = LocationProvider();
            provider.initializeWithDefaults();
            return provider;
          },
        ),
      ],
      child: const SafeAppWrapper(child: MyApp()),
    ),
  );
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    final themeProvider = Provider.of<ThemeProvider>(context);
    final localeProvider = Provider.of<LocaleProvider>(context);
    final authProvider = Provider.of<AuthProvider>(context);

    // Keys for navigation
    final rootNavigatorKey = GlobalKey<NavigatorState>();
    final shellNavigatorKey = GlobalKey<NavigatorState>();

    // Configure GoRouter with routes
    final router = GoRouter(
      navigatorKey: rootNavigatorKey,
      initialLocation: '/',
      debugLogDiagnostics: true,
      routes: [
        // Public routes (no bottom navigation)
        GoRoute(
          path: '/',
          name: 'splash',
          builder: (context, state) => const SplashScreen(),
        ),
        GoRoute(
          path: '/onboarding',
          name: 'onboarding',
          builder: (context, state) => const OnboardingScreen(),
        ),
        GoRoute(
          path: '/sign-in',
          name: 'sign-in',
          builder: (context, state) => const SignInScreen(),
        ),
        GoRoute(
          path: '/sign-up',
          name: 'sign-up',
          builder: (context, state) => const SignUpScreen(),
        ),
        GoRoute(
          path: '/car-details/:id',
          name: 'car-details',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => CarDetailsScreen(carId: state.pathParameters['id']!),
        ),
        GoRoute(
          path: '/book-car/:id',
          name: 'book-car',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => BookCarScreen(carId: state.pathParameters['id']!),
        ),
        GoRoute(
          path: '/document-upload/:bookingId/:carId',
          name: 'document-upload',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => DocumentUploadScreen(
            bookingId: state.pathParameters['bookingId']!,
            carId: state.pathParameters['carId']!,
          ),
        ),
        GoRoute(
          path: '/review-summary/:bookingId',
          name: 'review-summary',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => ReviewSummaryScreen(
            bookingId: state.pathParameters['bookingId']!,
          ),
        ),
        GoRoute(
          path: '/payment-methods/:bookingId',
          name: 'payment-methods-with-booking',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => PaymentMethodsScreen(
            bookingId: state.pathParameters['bookingId'] ?? '',
          ),
        ),
        GoRoute(
          path: '/payment-methods',
          name: 'payment-methods',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const PaymentMethodsScreen(bookingId: ''),
        ),
        GoRoute(
          path: '/payment-success/:bookingId',
          name: 'payment-success',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => PaymentSuccessScreen(
            bookingId: state.pathParameters['bookingId']!,
          ),
        ),
        GoRoute(
          path: '/e-receipt/:bookingId',
          name: 'e-receipt',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => EReceiptScreen(
            bookingId: state.pathParameters['bookingId']!,
          ),
        ),
        GoRoute(
          path: '/complete-profile',
          name: 'complete-profile',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const CompleteProfileScreen(),
        ),
        GoRoute(
          path: '/add-card',
          name: 'add-card',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const AddCardScreen(),
        ),
        GoRoute(
          path: '/search',
          name: 'search',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const SearchScreen(),
        ),
        GoRoute(
          path: '/notifications',
          name: 'notifications',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const NotificationsScreen(),
        ),
        GoRoute(
          path: '/enter-location',
          name: 'enter-location',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const EnterLocationScreen(),
        ),
        GoRoute(
          path: '/popular-cars',
          name: 'popular-cars',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) {
            final governorate = state.uri.queryParameters['governorate'] ?? '';
            return PopularCarsScreen(governorateId: governorate);
          },
        ),
        GoRoute(
          path: '/favorites',
          name: 'favorites',
          parentNavigatorKey: rootNavigatorKey,
          builder: (context, state) => const FavoritesScreen(),
        ),
        // Bottom navigation shell route
        ShellRoute(
          navigatorKey: shellNavigatorKey,
          builder: (context, state, child) {
            // Determine active page for bottom navigation
            int currentIndex = 0;
            final location = state.matchedLocation;

            switch (location) {
              case '/home':
                currentIndex = 0;
                break;
              case '/explore':
                currentIndex = 1;
                break;
              case '/my-bookings':
                currentIndex = 2;
                break;
              case '/chat':
                currentIndex = 3;
                break;
              case '/profile':
                currentIndex = 4;
                break;
            }

            return AppBottomNavigation(
              currentIndex: currentIndex,
              child: child,
            );
          },
          routes: [
            GoRoute(
              path: '/home',
              name: 'home',
              builder: (context, state) => const HomeScreen(),
            ),
            GoRoute(
              path: '/explore',
              name: 'explore',
              builder: (context, state) => const ExploreScreen(),
            ),
            GoRoute(
              path: '/my-bookings',
              name: 'my-bookings',
              builder: (context, state) => const MyBookingsScreen(),
            ),
            GoRoute(
              path: '/chat',
              name: 'chat',
              builder: (context, state) => const ChatScreen(),
            ),
            GoRoute(
              path: '/profile',
              name: 'profile',
              builder: (context, state) => const ProfileScreen(),
            ),
          ],
        ),
      ],
      // Route protection and redirection
      redirect: (context, state) async {
        final authProvider = Provider.of<AuthProvider>(context, listen: false);
        final publicRoutes = ['/', '/onboarding', '/sign-in', '/sign-up'];

        // Redirect to onboarding if first launch
        final prefs = await SharedPreferences.getInstance();
        final isFirstLaunch = prefs.getBool('first_launch') ?? true;
        if (isFirstLaunch && state.matchedLocation == '/') {
          return '/onboarding';
        }

        // Redirect to sign-in if not authenticated for protected routes
        if (!authProvider.isAuthenticated && !publicRoutes.contains(state.matchedLocation)) {
          return '/sign-in';
        }

        // Redirect to complete profile if needed
        if (authProvider.isAuthenticated) {
          final isProfileComplete = await authProvider.isProfileComplete();
          if (!isProfileComplete &&
              state.matchedLocation != '/complete-profile' &&
              !publicRoutes.contains(state.matchedLocation)) {
            return '/complete-profile';
          }
        }

        return null;
      },
    );

    return ScreenUtilInit(
      designSize: const Size(375, 812),
      minTextAdapt: true,
      splitScreenMode: true,
      builder: (context, child) {
        return MaterialApp.router(
          title: 'Nuvia Car Rental',
          debugShowCheckedModeBanner: false,
          theme: ThemeData(
            colorScheme: ColorScheme.fromSeed(
              seedColor: const Color(0xFF1E88E5),
              brightness: Brightness.light,
              primary: const Color(0xFF1E88E5),
              secondary: const Color(0xFFFFA726),
              surface: Colors.white,
            ),
            useMaterial3: true,
            fontFamily: 'Poppins',
            textTheme: TextTheme(
              headlineSmall: TextStyle(fontSize: 24.sp, fontWeight: FontWeight.bold),
              titleLarge: TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w600),
              bodyLarge: TextStyle(fontSize: 16.sp),
              bodyMedium: TextStyle(fontSize: 14.sp),
              bodySmall: TextStyle(fontSize: 12.sp),
            ),
            appBarTheme: AppBarTheme(
              centerTitle: true,
              elevation: 0,
              backgroundColor: Colors.transparent,
              foregroundColor: Colors.black87,
              titleTextStyle: TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w600),
            ),
            elevatedButtonTheme: ElevatedButtonThemeData(
              style: ElevatedButton.styleFrom(
                padding: EdgeInsets.symmetric(horizontal: 24.w, vertical: 12.h),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
                textStyle: TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w600),
              ),
            ),
            cardTheme: CardTheme(
              elevation: 2,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
              margin: EdgeInsets.symmetric(horizontal: 16.w, vertical: 8.h),
            ),
            inputDecorationTheme: InputDecorationTheme(
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
              contentPadding: EdgeInsets.symmetric(horizontal: 16.w, vertical: 12.h),
            ),
          ),
          darkTheme: ThemeData(
            colorScheme: ColorScheme.fromSeed(
              seedColor: const Color(0xFF1E88E5),
              brightness: Brightness.dark,
              primary: const Color(0xFF1E88E5),
              secondary: const Color(0xFFFFA726),
              surface: Colors.grey[900]!,
            ),
            useMaterial3: true,
            fontFamily: 'Poppins',
            textTheme: TextTheme(
              headlineSmall: TextStyle(fontSize: 24.sp, fontWeight: FontWeight.bold),
              titleLarge: TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w600),
              bodyLarge: TextStyle(fontSize: 16.sp),
              bodyMedium: TextStyle(fontSize: 14.sp),
              bodySmall: TextStyle(fontSize: 12.sp),
            ),
            appBarTheme: AppBarTheme(
              centerTitle: true,
              elevation: 0,
              backgroundColor: Colors.transparent,
              foregroundColor: Colors.white,
              titleTextStyle: TextStyle(fontSize: 20.sp, fontWeight: FontWeight.w600),
            ),
            elevatedButtonTheme: ElevatedButtonThemeData(
              style: ElevatedButton.styleFrom(
                padding: EdgeInsets.symmetric(horizontal: 24.w, vertical: 12.h),
                shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
                textStyle: TextStyle(fontSize: 16.sp, fontWeight: FontWeight.w600),
              ),
            ),
            cardTheme: CardTheme(
              elevation: 2,
              shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(12.r)),
              margin: EdgeInsets.symmetric(horizontal: 16.w, vertical: 8.h),
            ),
            inputDecorationTheme: InputDecorationTheme(
              border: OutlineInputBorder(borderRadius: BorderRadius.circular(12.r)),
              contentPadding: EdgeInsets.symmetric(horizontal: 16.w, vertical: 12.h),
            ),
          ),
          themeMode: themeProvider.themeMode,
          locale: localeProvider.locale,
          supportedLocales: AppLocalizations.supportedLocales,
          localizationsDelegates: const [
            AppLocalizations.delegate,
            GlobalMaterialLocalizations.delegate,
            GlobalWidgetsLocalizations.delegate,
            GlobalCupertinoLocalizations.delegate,
          ],
          routerConfig: router,
        );
      },
    );
  }
}